version: '3.8'

services:
  server:
    build: .
    container_name: spacetraders
    hostname: spacetraders
    env_file:
      - .env
    networks:
      - mynet
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - CALLSIGN=${CALLSIGN}
      - TOKEN=${TOKEN}
      - DEBUG=False

networks:
  mynet:
    driver: bridge